import Foundation

/// The symbols a workspace can be marked with. Colour on a workspace would
/// read as agent status, so a workspace is told apart by shape alone. None
/// of these is a check, exclamation, clock, bell, cross or plain disc: those
/// are the shapes status already uses.
public enum WorkspaceSymbols {
    public struct Symbol: Equatable, Sendable {
        public let name: String
        public let title: String
    }

    public struct Group: Sendable {
        public let title: String
        public let symbols: [Symbol]
    }

    /// The picker's sections, in order.
    public static let groups: [Group] = [
        Group(title: "Engineering", symbols: [
            Symbol(name: "square.stack.3d.up.fill", title: "Stack"),
            Symbol(name: "square.3.layers.3d", title: "Layers"),
            Symbol(name: "rectangle.stack.fill", title: "Cards"),
            Symbol(name: "cylinder.fill", title: "Database"),
            Symbol(name: "cylinder.split.1x2.fill", title: "Shards"),
            Symbol(name: "server.rack", title: "Server"),
            Symbol(name: "externaldrive.fill", title: "Drive"),
            Symbol(name: "icloud.fill", title: "Cloud service"),
            Symbol(name: "network", title: "Network"),
            Symbol(name: "arrow.triangle.branch", title: "Branch"),
            Symbol(name: "arrow.triangle.merge", title: "Merge"),
            Symbol(name: "arrow.triangle.pull", title: "Pull request"),
            Symbol(name: "curlybraces", title: "Code"),
            Symbol(name: "chevron.left.forwardslash.chevron.right", title: "Markup"),
            Symbol(name: "terminal.fill", title: "Terminal"),
            Symbol(name: "function", title: "Function"),
            Symbol(name: "cpu.fill", title: "Chip"),
            Symbol(name: "memorychip.fill", title: "Memory"),
            Symbol(name: "shippingbox.fill", title: "Package"),
            Symbol(name: "puzzlepiece.extension.fill", title: "Extension"),
            Symbol(name: "ladybug.fill", title: "Bug"),
            Symbol(name: "gearshape.2.fill", title: "Gears"),
            Symbol(name: "slider.horizontal.3", title: "Sliders"),
            Symbol(name: "switch.2", title: "Switches"),
            Symbol(name: "flowchart.fill", title: "Flowchart"),
            Symbol(name: "bolt.horizontal.fill", title: "Pipeline"),
            Symbol(name: "gauge.with.needle.fill", title: "Gauge"),
            Symbol(name: "lock.shield.fill", title: "Security"),
            Symbol(name: "antenna.radiowaves.left.and.right", title: "Signal"),
            Symbol(name: "safari.fill", title: "Browser"),
            Symbol(name: "brain.fill", title: "Brain"),
            Symbol(name: "cube.transparent.fill", title: "Model"),
            Symbol(name: "keyboard.fill", title: "Keyboard"),
            Symbol(name: "link", title: "Link"),
        ]),
        Group(title: "Work", symbols: [
            Symbol(name: "chart.bar.fill", title: "Chart"),
            Symbol(name: "chart.line.uptrend.xyaxis", title: "Trend"),
            Symbol(name: "chart.pie.fill", title: "Pie"),
            Symbol(name: "tablecells.fill", title: "Table"),
            Symbol(name: "square.grid.2x2.fill", title: "Grid"),
            Symbol(name: "list.bullet.rectangle.fill", title: "List"),
            Symbol(name: "doc.text.fill", title: "Document"),
            Symbol(name: "doc.on.doc.fill", title: "Copies"),
            Symbol(name: "folder.fill", title: "Folder"),
            Symbol(name: "archivebox.fill", title: "Archive"),
            Symbol(name: "tray.full.fill", title: "Inbox"),
            Symbol(name: "calendar", title: "Calendar"),
            Symbol(name: "envelope.fill", title: "Mail"),
            Symbol(name: "bubble.left.and.bubble.right.fill", title: "Chat"),
            Symbol(name: "person.2.fill", title: "Team"),
            Symbol(name: "megaphone.fill", title: "Megaphone"),
            Symbol(name: "newspaper.fill", title: "News"),
            Symbol(name: "chart.bar.doc.horizontal.fill", title: "Report"),
            Symbol(name: "briefcase.fill", title: "Briefcase"),
            Symbol(name: "paperclip", title: "Paperclip"),
            Symbol(name: "square.and.pencil", title: "Edit"),
            Symbol(name: "magnifyingglass", title: "Magnifier"),
            Symbol(name: "lightbulb.fill", title: "Bulb"),
            Symbol(name: "bookmark.fill", title: "Bookmark"),
        ]),
        Group(title: "Tools", symbols: [
            Symbol(name: "hammer.fill", title: "Hammer"),
            Symbol(name: "wrench.adjustable.fill", title: "Wrench"),
            Symbol(name: "wrench.and.screwdriver.fill", title: "Toolkit"),
            Symbol(name: "screwdriver.fill", title: "Screwdriver"),
            Symbol(name: "paintbrush.fill", title: "Brush"),
            Symbol(name: "paintbrush.pointed.fill", title: "Fine brush"),
            Symbol(name: "paintpalette.fill", title: "Palette"),
            Symbol(name: "pencil", title: "Pencil"),
            Symbol(name: "scissors", title: "Scissors"),
            Symbol(name: "ruler.fill", title: "Ruler"),
            Symbol(name: "flask.fill", title: "Flask"),
            Symbol(name: "testtube.2", title: "Test tubes"),
            Symbol(name: "atom", title: "Atom"),
            Symbol(name: "printer.fill", title: "Printer"),
            Symbol(name: "wand.and.stars", title: "Wand"),
            Symbol(name: "gearshape.fill", title: "Gear"),
        ]),
        Group(title: "Nature", symbols: [
            Symbol(name: "leaf.fill", title: "Leaf"),
            Symbol(name: "tree.fill", title: "Tree"),
            Symbol(name: "mountain.2.fill", title: "Mountains"),
            Symbol(name: "flame.fill", title: "Flame"),
            Symbol(name: "drop.fill", title: "Drop"),
            Symbol(name: "snowflake", title: "Snowflake"),
            Symbol(name: "sun.max.fill", title: "Sun"),
            Symbol(name: "moon.fill", title: "Moon"),
            Symbol(name: "moon.stars.fill", title: "Night"),
            Symbol(name: "cloud.fill", title: "Cloud"),
            Symbol(name: "cloud.rain.fill", title: "Rain"),
            Symbol(name: "cloud.bolt.fill", title: "Storm"),
            Symbol(name: "bolt.fill", title: "Bolt"),
            Symbol(name: "tornado", title: "Tornado"),
            Symbol(name: "rainbow", title: "Rainbow"),
            Symbol(name: "sparkles", title: "Sparkles"),
            Symbol(name: "wind", title: "Wind"),
            Symbol(name: "water.waves", title: "Waves"),
            Symbol(name: "carrot.fill", title: "Carrot"),
            Symbol(name: "globe.americas.fill", title: "Globe"),
            Symbol(name: "globe.europe.africa.fill", title: "Globe east"),
            Symbol(name: "globe.asia.australia.fill", title: "Globe south"),
        ]),
        Group(title: "Things", symbols: [
            Symbol(name: "paperplane.fill", title: "Paper plane"),
            Symbol(name: "gift.fill", title: "Gift"),
            Symbol(name: "crown.fill", title: "Crown"),
            Symbol(name: "cup.and.saucer.fill", title: "Cup"),
            Symbol(name: "mug.fill", title: "Mug"),
            Symbol(name: "wineglass.fill", title: "Wineglass"),
            Symbol(name: "fork.knife", title: "Cutlery"),
            Symbol(name: "birthday.cake.fill", title: "Cake"),
            Symbol(name: "gamecontroller.fill", title: "Controller"),
            Symbol(name: "dice.fill", title: "Dice"),
            Symbol(name: "puzzlepiece.fill", title: "Puzzle"),
            Symbol(name: "cube.fill", title: "Cube"),
            Symbol(name: "camera.fill", title: "Camera"),
            Symbol(name: "film.fill", title: "Film"),
            Symbol(name: "music.note", title: "Note"),
            Symbol(name: "guitars.fill", title: "Guitars"),
            Symbol(name: "pianokeys", title: "Piano"),
            Symbol(name: "headphones", title: "Headphones"),
            Symbol(name: "mic.fill", title: "Mic"),
            Symbol(name: "book.closed.fill", title: "Book"),
            Symbol(name: "books.vertical.fill", title: "Books"),
            Symbol(name: "graduationcap.fill", title: "Cap"),
            Symbol(name: "backpack.fill", title: "Backpack"),
            Symbol(name: "bag.fill", title: "Bag"),
            Symbol(name: "cart.fill", title: "Cart"),
            Symbol(name: "creditcard.fill", title: "Credit card"),
            Symbol(name: "banknote.fill", title: "Banknote"),
            Symbol(name: "key.fill", title: "Key"),
            Symbol(name: "lock.fill", title: "Lock"),
            Symbol(name: "tag.fill", title: "Tag"),
            Symbol(name: "pin.fill", title: "Pin"),
            Symbol(name: "map.fill", title: "Map"),
            Symbol(name: "binoculars.fill", title: "Binoculars"),
            Symbol(name: "umbrella.fill", title: "Umbrella"),
            Symbol(name: "theatermasks.fill", title: "Masks"),
            Symbol(name: "trophy.fill", title: "Trophy"),
            Symbol(name: "medal.fill", title: "Medal"),
            Symbol(name: "balloon.fill", title: "Balloon"),
            Symbol(name: "party.popper.fill", title: "Party"),
            Symbol(name: "house.fill", title: "House"),
            Symbol(name: "building.2.fill", title: "Buildings"),
            Symbol(name: "building.columns.fill", title: "Columns"),
            Symbol(name: "tent.fill", title: "Tent"),
            Symbol(name: "lamp.desk.fill", title: "Lamp"),
            Symbol(name: "sofa.fill", title: "Sofa"),
            Symbol(name: "tshirt.fill", title: "T-shirt"),
            Symbol(name: "eyeglasses", title: "Glasses"),
        ]),
        Group(title: "Travel and sport", symbols: [
            Symbol(name: "airplane", title: "Airplane"),
            Symbol(name: "car.fill", title: "Car"),
            Symbol(name: "bus.fill", title: "Bus"),
            Symbol(name: "tram.fill", title: "Tram"),
            Symbol(name: "bicycle", title: "Bicycle"),
            Symbol(name: "sailboat.fill", title: "Sailboat"),
            Symbol(name: "ferry.fill", title: "Ferry"),
            Symbol(name: "fuelpump.fill", title: "Fuel"),
            Symbol(name: "signpost.right.fill", title: "Signpost"),
            Symbol(name: "figure.run", title: "Runner"),
            Symbol(name: "figure.hiking", title: "Hiker"),
            Symbol(name: "soccerball", title: "Football"),
            Symbol(name: "basketball.fill", title: "Basketball"),
            Symbol(name: "baseball.fill", title: "Baseball"),
            Symbol(name: "tennis.racket", title: "Racket"),
            Symbol(name: "skateboard.fill", title: "Skateboard"),
        ]),
        Group(title: "Shapes", symbols: [
            Symbol(name: "triangle.fill", title: "Triangle"),
            Symbol(name: "diamond.fill", title: "Diamond"),
            Symbol(name: "square.fill", title: "Square"),
            Symbol(name: "hexagon.fill", title: "Hexagon"),
            Symbol(name: "pentagon.fill", title: "Pentagon"),
            Symbol(name: "octagon.fill", title: "Octagon"),
            Symbol(name: "rhombus.fill", title: "Rhombus"),
            Symbol(name: "seal.fill", title: "Seal"),
            Symbol(name: "star.fill", title: "Star"),
            Symbol(name: "heart.fill", title: "Heart"),
            Symbol(name: "shield.fill", title: "Shield"),
            Symbol(name: "suit.club.fill", title: "Club"),
            Symbol(name: "suit.spade.fill", title: "Spade"),
        ]),
        Group(title: "Animals", symbols: [
            Symbol(name: "bird.fill", title: "Bird"),
            Symbol(name: "fish.fill", title: "Fish"),
            Symbol(name: "hare.fill", title: "Hare"),
            Symbol(name: "tortoise.fill", title: "Tortoise"),
            Symbol(name: "pawprint.fill", title: "Paw"),
        ]),
    ]

    /// Assigned first, being the most unlike one another.
    static let assignedFirst = [
        "square.stack.3d.up.fill", "cylinder.fill", "curlybraces", "terminal.fill",
        "arrow.triangle.branch", "server.rack", "cpu.fill", "shippingbox.fill",
        "hammer.fill", "flask.fill", "chart.bar.fill", "globe.americas.fill",
        "bolt.fill", "leaf.fill", "cube.fill", "puzzlepiece.fill",
        "paperplane.fill", "key.fill", "brain.fill", "gearshape.2.fill",
    ]

    /// In the order workspaces are assigned them.
    public static let all: [Symbol] = {
        let every = groups.flatMap(\.symbols)
        let lead = assignedFirst.compactMap { name in every.first { $0.name == name } }
        return lead + every.filter { !assignedFirst.contains($0.name) }
    }()

    public static func contains(_ name: String) -> Bool {
        all.contains { $0.name == name }
    }
}
